config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  get '/top' => "homes#top"
  resources :books
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @books = Book.all
    @book = Book.new
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:complete] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
    @books = Book.all
      render :index
    end
  end

  def show
   @book = Book.find(params[:id])
   
    
  end

  def edit
    @book = Book.find(params[:id])

  end
  
  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:complete] = "Book was successfully created." 
    redirect_to book_path(@book.id)  
   else
    @books = Book.all
    render :edit
   end 
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <p><%= f.text_area :body %></p>
	
  <p><%= f.submit 'Update Book' %></p>
  
<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= "|" %>
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </tr>
    
  </thead>

  <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <p><%= book.title %> </p>
        </td>
        <td>
          <p><%= book.body %></p>
        </td>
        <td> 
          <p><%= link_to "Show", book_path(book.id) %></p>
        </td>
        <td>
          <p><%= link_to "Edit", edit_book_path(book.id) %></p>
        </td>
        <td>
          <p><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure ?" %></p>
        </td>
      </tr>
      <% end %>
  </tbody>

  
<table>
<h2>New book</h2>
<%= form_with model: @book, url: '/books', method: :post do |f| %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <div>
    <p>Title</p>
    <%= f.text_field :title %>
  </div>

  <div>
    <p>Body</p>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.submit 'Create Book' %>
  </div>
<% end %>
</table>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<%= flash[:complete] %> 
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<p>
 <strong>Body:</strong>
 <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= "|" %>
<%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>

<%= link_to "start", "/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>